export const hostUrl = 'https://dev-aiaas4-50.lingban.cn'
export const wsUrl = 'wss://testipcc.lingban.cn/janus'
export const aiaasWsUrl = 'wss://dev-aiaas4-50.lingban.cn'
export const rtmpUrl = 'rtmp://testipcc.lingban.cn/'
export const mqWsUrl = 'wss://mq-aiaas4test.lingban.cn/ws'
